### ISSUE TITLE
question regarding .map files

### ISSUE THREAD

**Issue by andriijas** [meleyal/git-digest-brunch#4]
Hi meleyal

This is not an issue more a personal question. Sorry for any inconvenience.

How do you make sure eventual .map files are cleaned out and removed from your public dir when building production?

Thanks

**Comment by meleyal** [comment]
It's been a while since I've used brunch, but according to the docs source maps are not generated with `brunch build --production`:

https://github.com/brunch/brunch/blob/stable/docs/commands.md#brunch-build

**Comment by andriijas** [comment]
no they are not but but old file from previous builds remains. anyway,  thanks for your effort.  Have you moved on to gulp or something else?

**Comment by meleyal** [comment]
I think I was just nuking the entire public dir when building, e.g. here's the scripts field from my package.json:

``` javascript
"scripts": {
    "start": "brunch watch --server --port 5000",
    "build": "touch public && rm -r public && brunch build --production"
},
```

The simplest alternative I've found so far is just [npm run + browserify](http://substack.net/task_automation_with_npm_run). Nothing beats Brunch for simplicity though.
